### PR TITLE
Added Undo Functionality

### PR DESCRIPTION
**Pull request by prateek1998**
You are doing Great work..

### CODE REVIEW

**Comment by PlytonRexus** [comment]
Hey @prateek1998 ,
Could you maybe mention the changes you made in a short summary? I'd love to merge this PR but I am slightly sceptical of the number of lines that got changed. Hope you don't mind! Thanks for the effort!

**Comment by PlytonRexus** [comment]
I see a lot of changes have been in the [package-lock.json](https://github.com/PlytonRexus/chain-reaction/pull/9/files#diff-32607347f8126e6534ebc7ebaec4853d) file. Why would we change that?

**Comment by prateek1998** [comment]
Things performed
1. Make statusHistory an array.
2. Enable the Undo button functionality.
3. Store the previous State so that when undo is performed then , we call the previous State.
4. Added Necessary Functions which will run after the Undo is performed like Switch Turn ,TurnUtils  etc.

Note : I only changed index.js file and package file is auto changed by npm.

**Comment by PlytonRexus** [comment]
There. Done! A lot of thanks, @prateek1998 .

**Pull request merged**
